version: '3.8'
services:
  busybox:
    container_name: busybox
    image: busybox:latest
    volumes:
      - myvolume:/workdir
    command: chown -R 1000:1000 /workdir
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - myvolume:/usr/src
    depends_on:
      - busybox
  yocto_pi:
    hostname: yocto
    container_name: yocto_pi
    build: .
    volumes:
      - myvolume:/home/yocto/build
    command: bash
    stdin_open: true
    tty: true
    depends_on:
      - busybox

volumes:
  myvolume:
    external: false
